require("lspsaga").setup()
local map = vim.keymap.set
map("n", "<leader>ic", [[<cmd> Lspsaga incoming_calls <cr>]], { desc = "Lspsaga incoming calls" })
map("n", "<leader>oc", [[<cmd> Lspsaga outgoing_calls <cr>]], { desc = "Lspsaga outgoing calls" })
map("n", "<leader>lc", [[<cmd> Lspsaga code_action <cr>]], { desc = "Lspsaga code actions" })
map("n", "<leader>dn", [[<cmd> Lspsaga peek_definition <cr>]], { desc = "Lspsaga peek definition" })
map("n", "<leader>td", [[<cmd> Lspsaga peek_type_definition <cr>]], { desc = "Lspsaga peek type definition" })
map("n", "<leader>dn", [[<cmd> Lspsaga diagnostic_jump_next <cr>]], { desc = "Lspsaga jump to next diagnostic" })
map("n", "<leader>dp", [[<cmd> Lspsaga diagnostic_jump_prev <cr>]], { desc = "Lspsaga jump to prev diagnostic" })
map("n", "<leader>fi", [[<cmd> Lspsaga finder imp <cr>]], { desc = "Lspsaga finder implementation" })
map("n", "<leader>fr", [[<cmd> Lspsaga finder ref <cr>]], { desc = "Lspsaga finder references" })
map("n", "<leader>fd", [[<cmd> Lspsaga finder def <cr>]], { desc = "Lspsaga finder definition" })
map({ "n", "t" }, "<A-i>", [[<cmd> Lspsaga term_toggle <cr>]], { desc = "Lspsaga toggle terminal" })
map("n", "<leader>k", [[<cmd> Lspsaga hover_doc <cr>]], { desc = "Lspsaga hover documentation" })
map("n", "<leader>ol", [[<cmd> Lspsaga outline <cr>]], { desc = "Lspsaga show outline of current buffer" })
map("n", "<leader>rn", [[<cmd> Lspsaga rename <cr>]], { desc = "Lspsaga rename" })
