require("nvim-treesitter.configs").setup {
  ensure_installed = {
    "lua",
    "vim",
    "vimdoc",
    "query",
    "json",
    "yaml",
    "markdown",
    "printf",
    "toml",
    "markdown_inline",
    "bash",
    "go",
    "gomod",
    "gowork",
    "gosum",
    "python",
    "regex",
    "html",
  },
  highlight = { enable = true },
}
